name: Run Selenium Script

on:
  push:
    branches: [main]

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.5

      - name: Install dependencies
        run: |
          pip install selenium
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -N https://chromedriver.storage.googleapis.com/113.0.5672.63/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          sudo apt-get install -y chromium-browser

      - name: Run Selenium script
        run: python test.py
